global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'proxy'
    static_configs:
      - targets: ['localhost:8080']  # our proxy metrics endpoint
    metrics_path: '/metrics'
    scheme: 'http'